// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ryuptlhyneuyzvyodmjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dXB0bGh5bmV1eXp2eW9kbWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxNTM0NzUsImV4cCI6MjA4MTcyOTQ3NX0.BmYWmPJWkvx4eo5w3TQpeqSHMBY7cusjq8RixpequzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);